
def test_case_7_Verify_Employee_Name_Autocomplete_Suggestion(app):
    app.orangeHrm.openUrl()
    app.orangeHrm.login_to_the_application()
    app.orangeHrm.sideMenu.click_on_side_menu_button('HR Administration')
    app.orangeHrm.hrAdministration.click_on_filter()
    app.orangeHrm.popUp.set_employee_name('Odis')
    app.assert_that(app.orangeHrm.popUp.get_autocomplete_names()).contains('Odis Adalwin', 'Kgosi Modise')

def test_case_7_1_Verify_No_Results_Found_Error_Message(app):
    app.orangeHrm.openUrl()
    app.orangeHrm.login_to_the_application()
    app.orangeHrm.sideMenu.click_on_side_menu_button('HR Administration')
    app.orangeHrm.hrAdministration.click_on_filter()
    app.orangeHrm.popUp.set_employee_name('Murat')
    app.assert_that(app.orangeHrm.popUp.get_no_results_message()).is_equal_to('No results found')

def test_case_7_2_Verify_Dropdown_Default_Values(app):
    app.orangeHrm.openUrl()
    app.orangeHrm.login_to_the_application()
    app.assert_that(app.orangeHrm.get_header_text()).is_equal_to('Employee Management')
    app.orangeHrm.sideMenu.click_on_side_menu_button('HR Administration')
    app.orangeHrm.hrAdministration.click_on_filter()
    app.assert_that(app.orangeHrm.popUp.get_ess_role_dropdown_values()).is_equal_to(['All','Default ESS'])
    app.assert_that(app.orangeHrm.popUp.get_admin_role_dropdown_values()).is_equal_to(['All', 'Global Admin', 'Leave Admin', 'Regional HR Admin', 'Report Admin'])
    app.assert_that(app.orangeHrm.popUp.get_supervisor_role_dropdown_values()).is_equal_to(['All', 'Default Supervisor'])
    app.assert_that(app.orangeHrm.popUp.get_status_dropdown_values()).is_equal_to(['All', 'Enabled', 'Disabled'])
    app.assert_that(app.orangeHrm.popUp.get_location_dropdown_values()).is_equal_to(['-- Select --', 'All', 'Australia', 'Australia office', 'Canada', 'Canadian Development Center', 'France', 'France Office', 'Germany', 'German Office', 'India', 'India Office', 'Jamaica', 'Jamaica training center', 'Mexico', 'Mexico Office', 'Philippines', 'Philippine call center', 'Singapore', 'Singapore Regional HQ', 'South Africa', 'South Africa Satellite Office', 'United Kingdom', 'UK Office', 'United States', 'US Office'])

def test_case_7_3_Verify_Reset_Button_Functionality(app):
    app.orangeHrm.openUrl()
    app.orangeHrm.login_to_the_application()
    app.assert_that(app.orangeHrm.get_header_text()).is_equal_to('Employee Management')
    app.orangeHrm.sideMenu.click_on_side_menu_button('HR Administration')
    app.orangeHrm.hrAdministration.click_on_filter()
    # app.orangeHrm.popUp.set_hr_administration_drop_downs(ess_role="Default ESS", user_name="Admin")
    app.orangeHrm.popUp.set_username("Admin")
    app.orangeHrm.popUp.set_employee_name("wer")
    app.orangeHrm.popUp.set_ess_role_input_dropdown("Default ESS")
    app.orangeHrm.popUp.set_admin_role_input_dropdown("Leave Admin")
    app.orangeHrm.popUp.set_supervisor_role_dropdown("Default Supervisor")
    app.orangeHrm.popUp.set_status_input_dropdown("Disabled")
    app.orangeHrm.popUp.set_location_input_dropdown("Australia")
    app.orangeHrm.popUp.click_on_filter_reset_button()
    app.orangeHrm.popUp.wait_filter_pop_up_stop_displayed()
    app.orangeHrm.hrAdministration.click_on_filter()
    app.assert_that(app.orangeHrm.popUp.get_ess_role_selected_dropdown_value()).is_equal_to("All")
    app.assert_that(app.orangeHrm.popUp.get_admin_role_selected_dropdown_value()).is_equal_to("All")
    app.assert_that(app.orangeHrm.popUp.get_supervisor_role_selected_dropdown_value()).is_equal_to("All")
    app.assert_that(app.orangeHrm.popUp.get_status_selected_dropdown_value()).is_empty()
    app.assert_that(app.orangeHrm.popUp.get_location_selected_dropdown_value()).is_equal_to("All")

def test_case_7_4_Verify_Cancel_Button_Functionality(app):
    app.orangeHrm.openUrl()
    app.orangeHrm.login_to_the_application()
    app.assert_that(app.orangeHrm.get_header_text()).is_equal_to('Employee Management')
    app.orangeHrm.sideMenu.click_on_side_menu_button('HR Administration')
    app.orangeHrm.hrAdministration.click_on_filter()
    app.orangeHrm.popUp.click_on_filter_reset_button()
    app.orangeHrm.popUp.wait_filter_pop_up_stop_displayed()
    app.orangeHrm.hrAdministration.click_on_filter()
    app.orangeHrm.popUp.set_username("Admin")
    app.orangeHrm.popUp.set_employee_name("wer")
    app.orangeHrm.popUp.set_ess_role_input_dropdown("Default ESS")
    app.orangeHrm.popUp.set_admin_role_input_dropdown("Leave Admin")
    app.orangeHrm.popUp.set_supervisor_role_dropdown("Default Supervisor")
    app.orangeHrm.popUp.set_status_input_dropdown("Disabled")
    app.orangeHrm.popUp.set_location_input_dropdown("Australia")
    app.orangeHrm.popUp.click_on_filter_cancel_button()
    app.orangeHrm.popUp.wait_filter_pop_up_stop_displayed()
    app.orangeHrm.hrAdministration.click_on_filter()
    app.assert_that(app.orangeHrm.popUp.get_ess_role_selected_dropdown_value()).is_equal_to("Default ESS")
    app.assert_that(app.orangeHrm.popUp.get_admin_role_selected_dropdown_value()).is_equal_to("Leave Admin")
    app.assert_that(app.orangeHrm.popUp.get_supervisor_role_selected_dropdown_value()).is_equal_to("Default Supervisor")
    app.assert_that(app.orangeHrm.popUp.get_status_selected_dropdown_value()).is_equal_to("Disabled")
    app.assert_that(app.orangeHrm.popUp.get_location_selected_dropdown_value()).contains("Australia office")